name: 'wake-up-ec2-runners'
description: 'A Github Action to wake up AWS EC2 runners'
inputs:
  aws-region:
    description: 'Override AWS Region to search for EC2 instances'
  concurrency:
    description: 'How many concurrent job runners does this workflow need'
  tags:
    description: 'JSON Serialized object with <tagname>:<tagvalue> pairs'
runs:
  using: 'node12'
  main: 'dist/index.js'
